# Generated by Django 6.0.5 on 2026-07-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_is_temporary_chatsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
