FROM python:3.11-slim

WORKDIR /app

# Actualizar pip
RUN pip install --upgrade pip

# Instalar dependencias del sistema (para psycopg2 y otras)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar dependencias de Python
COPY requirements-docker.txt .
RUN pip install --no-cache-dir -r requirements-docker.txt

# Copiar proyecto
COPY . .

EXPOSE 8000
