# Generated by Django 6.0 on 2026-05-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Nueva sesión', max_length=200),
        ),
    ]
